version: '3'

services:
    app:
        build: .
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000
        ports:
            - "8080:8000"
        volumes:
            - /home/wern98332/sidus-heroes/app:/code/app
        container_name: test-job
        restart: always
        environment:
            - PSQL_USER=gen_user
            - PSQL_PASSWORD=Rdfynjdfybt2022
            - PSQL_HOST=85.193.81.33
            - PSQL_PORT=5432
            - PSQL_DATABASE=default_db
            - REDIS_HOST=redis_db
            - REDIS_PORT=6379
        depends_on:
            - redis_db
    redis_db:
        image: redis:6
        container_name: redis-db
        restart: always
        volumes:
            - /home/wern98332/sidus-heroes/redis:/usr/local/etc/redis/redis.conf
        ports:
            - "6379:6379"
